image_index = 0;
globalvar tmd_base;
tmd_base = -1;
globalvar tmd_edit;
tmd_edit = -1;
globalvar mm0_base_buffer;
mm0_base_buffer = -1;
globalvar tmd_edit_buffer;
tmd_edit_buffer = -1;
globalvar fname_mm0;
fname_mm0 = "";
globalvar ui_name_mm0;
ui_name_mm0 = "";
globalvar prim_list;
prim_list = [];
globalvar vert_list;
vert_list = [];
globalvar tmd_edit_flag;
tmd_edit_flag = 0;